import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import favicon from './favicon.ico';

// Importa la fuente Poppins desde next/font/google con el peso especificado
const poppins = Poppins({ 
  subsets: ['latin'], 
  weight: ['200', '600']
});

export const metadata: Metadata = {
  title: "Grupo DEMAT",
  description: "Generated by create next app",
  icons: {
    icon: favicon.src,
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${poppins.className} h-screen`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Montserrat } from 'next/font/google';
// import "./globals.css";
// import Navbar from "@/components/navbar";
// import Footer from "@/components/footer";

// // Importa la fuente Montserrat desde next/font/google
// const montserrat = Montserrat({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Grupo DEMAT",
//   description: "Grupo ferretero DEMAT",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="es">
//       <body className={montserrat.className}>
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }

